"""Phase 1-D: annotator A (Claude, reading each example under guide v1.0) labels for the golden set.
Kept as code so the pass is reproducible and diffable. Writes data/golden/golden_annotatorA.csv.
"""
import pandas as pd

from resolveai import config

# gid: (intent, should_escalate, escalation_reason, note)
A = {
    "g000": ("hardware_damage", True, "hardware", "speaker stopped after jack issue; component failure"),
    "g001": ("performance_crash", False, "none", ""),
    "g002": ("account_store_repair", True, "private_info", "open case, 22 days"),
    "g003": ("performance_crash", False, "none", "answering brand's backup question"),
    "g004": ("data_loss_sync", False, "none", "public steps: iCloud Photos / Recently Deleted"),
    "g005": ("keyboard_text_bug", False, "none", ""),
    "g006": ("performance_crash", False, "none", "Settings app crash"),
    "g007": ("apps_services", False, "none", "individual plan = one stream; explainable publicly"),
    "g008": ("account_store_repair", True, "private_info", "repair ID"),
    "g009": ("connectivity", False, "none", ""),
    "g010": ("connectivity", False, "none", "profanity but symptom present"),
    "g011": ("general_complaint", False, "none", "no symptom; clarify. mild profanity, not abuse"),
    "g012": ("account_store_repair", True, "private_info", "repair number, Brazil"),
    "g013": ("apps_services", False, "none", "purchased album won't play; sign-out/in steps"),
    "g014": ("battery_power", False, "none", "how-to question"),
    "g015": ("apps_services", False, "none", "HARD: OS auto-update mechanics -> apps_services (guide note)"),
    "g016": ("performance_crash", False, "none", ""),
    "g017": ("non_english", False, "none", ""),
    "g018": ("apps_services", False, "none", "Watch activity sync"),
    "g019": ("account_store_repair", True, "private_info", ""),
    "g020": ("keyboard_text_bug", False, "none", ""),
    "g021": ("keyboard_text_bug", False, "none", ""),
    "g022": ("apps_services", False, "none", "podcasts/AirPods controls"),
    "g023": ("performance_crash", False, "none", ""),
    "g024": ("connectivity", False, "none", "HARD: accessory not supported -> connectivity (guide note)"),
    "g025": ("other", False, "none", "closure: fixed"),
    "g026": ("performance_crash", False, "none", ""),
    "g027": ("connectivity", False, "none", "first symptom wifi"),
    "g028": ("other", False, "none", "product availability"),
    "g029": ("apps_services", True, "repeat_contact", "restarted several times, problem remains"),
    "g030": ("performance_crash", False, "none", "Dec-2 respring bug; public fix = update"),
    "g031": ("battery_power", False, "none", ""),
    "g032": ("keyboard_text_bug", False, "none", ""),
    "g033": ("general_complaint", False, "none", ""),
    "g034": ("apps_services", False, "none", "Siri"),
    "g035": ("account_store_repair", False, "none", "public answer: choose None as payment"),
    "g036": ("data_loss_sync", False, "none", "clarify"),
    "g037": ("general_complaint", False, "none", ""),
    "g038": ("battery_power", False, "none", ""),
    "g039": ("apps_services", False, "none", "camera settings; screenshot reply"),
    "g040": ("apps_services", False, "none", "Mail"),
    "g041": ("performance_crash", False, "none", ""),
    "g042": ("apps_services", False, "none", "Apple Pay Cash how-to"),
    "g043": ("keyboard_text_bug", False, "none", ""),
    "g044": ("account_store_repair", True, "private_info", "payment rejected"),
    "g045": ("battery_power", False, "none", "public: battery service info"),
    "g046": ("other", False, "none", "sales question"),
    "g047": ("other", False, "none", "thanks"),
    "g048": ("other", True, "repeat_contact", "HARD: asks about an existing DM -> human must check (guide note)"),
    "g049": ("account_store_repair", True, "private_info", "wrong order delivered"),
    "g050": ("apps_services", False, "none", "Apple Pay Cash rollout"),
    "g051": ("battery_power", False, "none", "screenshot reply"),
    "g052": ("apps_services", False, "none", "Podcasts settings"),
    "g053": ("other", False, "none", "closure"),
    "g054": ("battery_power", False, "none", ""),
    "g055": ("battery_power", False, "none", ""),
    "g056": ("apps_services", False, "none", "update not installing (see g015)"),
    "g057": ("other", False, "none", "feature request"),
    "g058": ("account_store_repair", True, "private_info", "billing alert"),
    "g059": ("other", False, "none", "closure: resolved"),
    "g060": ("other", False, "none", "HARD: parental-controls how-to; article suffices"),
    "g061": ("keyboard_text_bug", False, "none", ""),
    "g062": ("general_complaint", False, "none", "clarify"),
    "g063": ("general_complaint", False, "none", "unknown pop-up, screenshot"),
    "g064": ("data_loss_sync", False, "none", "first symptom photos"),
    "g065": ("connectivity", True, "repeat_contact", "visited store, deep thread, unresolved"),
    "g066": ("non_english", False, "none", ""),
    "g067": ("performance_crash", False, "none", ""),
    "g068": ("battery_power", False, "none", ""),
    "g069": ("connectivity", False, "none", "network shares after patch"),
    "g070": ("non_english", False, "none", "Dutch"),
    "g071": ("keyboard_text_bug", False, "none", ""),
    "g072": ("hardware_damage", True, "safety", "cable smoking"),
    "g073": ("battery_power", False, "none", "context carries symptom"),
    "g074": ("performance_crash", False, "none", ""),
    "g075": ("data_loss_sync", False, "none", "migration how-to"),
    "g076": ("other", False, "none", "compatibility question"),
    "g077": ("performance_crash", False, "none", ""),
    "g078": ("data_loss_sync", False, "none", "iTunes backup greyed out"),
    "g079": ("performance_crash", False, "none", ""),
    "g080": ("apps_services", False, "none", "iMessage"),
    "g081": ("keyboard_text_bug", False, "none", ""),
    "g082": ("non_english", False, "none", "Arabic"),
    "g083": ("other", False, "none", "thanks"),
    "g084": ("apps_services", False, "none", "visual voicemail"),
    "g085": ("general_complaint", False, "none", "screenshot only"),
    "g086": ("apps_services", False, "none", "Music app"),
    "g087": ("connectivity", False, "none", "HARD: Beats audio issue; clarify (guide note)"),
    "g088": ("performance_crash", False, "none", ""),
    "g089": ("performance_crash", False, "none", "Face ID + freezes"),
    "g090": ("keyboard_text_bug", False, "none", "emoji issue; clarify"),
    "g091": ("non_english", False, "none", ""),
    "g092": ("hardware_damage", True, "hardware", "touch screen dead, no receipt"),
    "g093": ("data_loss_sync", False, "none", ""),
    "g094": ("performance_crash", False, "none", "Mac freezes"),
    "g095": ("other", False, "none", "thanks"),
    "g096": ("apps_services", True, "repeat_contact", "tried resets; Phone app blank"),
    "g097": ("apps_services", False, "none", "conference call"),
    "g098": ("performance_crash", False, "none", ""),
    "g099": ("keyboard_text_bug", True, "safety", "self-harm statement, even if hyperbole"),
    "g100": ("non_english", False, "none", "French"),
    "g101": ("general_complaint", False, "none", "rant, no symptom"),
    "g102": ("performance_crash", False, "none", ""),
    "g103": ("performance_crash", False, "none", ""),
    "g104": ("hardware_damage", True, "hardware", "LCD lines"),
    "g105": ("battery_power", False, "none", "'same here' in battery thread"),
    "g106": ("apps_services", False, "none", "Mail"),
    "g107": ("apps_services", False, "none", "Clock"),
    "g108": ("apps_services", True, "repeat_contact", "tried toggling/rebooting"),
    "g109": ("battery_power", False, "none", ""),
    "g110": ("data_loss_sync", False, "none", "texts deleted first"),
    "g111": ("data_loss_sync", True, "repeat_contact", "already reset/logged out-in"),
    "g112": ("general_complaint", False, "none", ""),
    "g113": ("other", False, "none", "off-topic"),
    "g114": ("apps_services", False, "none", "alarms first; then freezing"),
    "g115": ("apps_services", False, "none", "camera"),
    "g116": ("general_complaint", False, "none", "screenshot, unknown messages"),
    "g117": ("performance_crash", False, "none", ""),
    "g118": ("general_complaint", True, "vague_hostile", "abuse, no symptom"),
    "g119": ("other", False, "none", "product availability"),
    "g120": ("data_loss_sync", False, "none", ""),
    "g121": ("apps_services", True, "repeat_contact", "recurring 3x, restart needed"),
    "g122": ("battery_power", False, "none", ""),
    "g123": ("performance_crash", False, "none", ""),
    "g124": ("performance_crash", False, "none", ""),
    "g125": ("keyboard_text_bug", False, "none", "HARD: thread has freezing AND I.T; guide rule says keyboard wins"),
    "g126": ("data_loss_sync", True, "repeat_contact", "3rd time, abusive"),
    "g127": ("account_store_repair", True, "hardware", "warranty repair request"),
    "g128": ("connectivity", False, "none", "GPS"),
    "g129": ("other", False, "none", ""),
    "g130": ("data_loss_sync", False, "none", "messages missing"),
    "g131": ("connectivity", True, "repeat_contact", "SIM invalid, retried many times"),
    "g132": ("account_store_repair", True, "private_info", "charged after cancel"),
    "g133": ("hardware_damage", True, "safety", "smoke; open case"),
    "g134": ("apps_services", False, "none", "Safari"),
    "g135": ("apps_services", False, "none", "11.2 camera focus bug"),
    "g136": ("apps_services", False, "none", "App Store previews"),
    "g137": ("connectivity", True, "repeat_contact", "no response, tried on other phone"),
    "g138": ("data_loss_sync", False, "none", ""),
    "g139": ("non_english", False, "none", ""),
    "g140": ("non_english", False, "none", ""),
    "g141": ("apps_services", True, "repeat_contact", "followed suggestion, persists"),
    "g142": ("general_complaint", False, "none", "no symptom"),
    "g143": ("non_english", False, "none", ""),
    "g144": ("keyboard_text_bug", False, "none", ""),
    "g145": ("other", False, "none", "phishing check"),
    "g146": ("apps_services", False, "none", "HARD: macOS root security -> apps_services (guide note)"),
    "g147": ("connectivity", False, "none", ""),
    "g148": ("connectivity", False, "none", "wifi sync"),
    "g149": ("other", False, "none", "how-to"),
    "g150": ("non_english", False, "none", ""),
    "g151": ("hardware_damage", True, "hardware", "speaker blew"),
    "g152": ("connectivity", True, "repeat_contact", "2 brand turns, no progress"),
    "g153": ("account_store_repair", False, "none", "HARD: complaint about security delay; explainable publicly"),
    "g154": ("data_loss_sync", False, "none", "notes lost"),
    "g155": ("account_store_repair", True, "private_info", "AppleCare case"),
    "g156": ("other", False, "none", "closure"),
    "g157": ("account_store_repair", True, "private_info", "number transfer, case"),
    "g158": ("apps_services", False, "none", "iTunes sync"),
    "g159": ("account_store_repair", True, "private_info", "2FA blocks appointment"),
    "g160": ("keyboard_text_bug", False, "none", ""),
    "g161": ("other", False, "none", "closure"),
    "g162": ("apps_services", True, "repeat_contact", "2 brand turns; app not in store"),
    "g163": ("performance_crash", False, "none", ""),
    "g164": ("apps_services", False, "none", "version reply"),
    "g165": ("non_english", False, "none", ""),
    "g166": ("connectivity", True, "repeat_contact", "reset network settings already"),
    "g167": ("data_loss_sync", False, "none", ""),
    "g168": ("general_complaint", False, "none", ""),
    "g169": ("general_complaint", False, "none", ""),
    "g170": ("apps_services", False, "none", "macOS root (see g146)"),
    "g171": ("account_store_repair", True, "private_info", "appointment blocked by 2FA"),
    "g172": ("non_english", False, "none", "Portuguese, abusive"),
    "g173": ("apps_services", False, "none", "clarify"),
    "g174": ("keyboard_text_bug", False, "none", ""),
    "g175": ("data_loss_sync", False, "none", ""),
    "g176": ("performance_crash", False, "none", ""),
    "g177": ("hardware_damage", True, "safety", "Watch burn"),
    "g178": ("account_store_repair", True, "private_info", "Apple ID email mismatch"),
    "g179": ("data_loss_sync", False, "none", "iCloud Photos toggle"),
    "g180": ("apps_services", False, "none", "language changed"),
    "g181": ("data_loss_sync", False, "none", "storage"),
    "g182": ("apps_services", False, "none", "iTunes sync ringtones"),
    "g183": ("performance_crash", False, "none", ""),
    "g184": ("performance_crash", False, "none", "Mac hot after update"),
    "g185": ("connectivity", False, "none", "HARD: 'service down' ambiguous"),
    "g186": ("apps_services", False, "none", "HARD: refuses DM; public answer exists (rollout)"),
    "g187": ("battery_power", False, "none", ""),
    "g188": ("non_english", False, "none", ""),
    "g189": ("battery_power", False, "none", "AirPods case won't charge"),
    "g190": ("other", False, "none", "suggestion"),
    "g191": ("battery_power", True, "repeat_contact", "followed steps, 'what's next'"),
    "g192": ("performance_crash", False, "none", "abusive but symptom"),
    "g193": ("performance_crash", False, "none", ""),
    "g194": ("apps_services", False, "none", "Apple Music"),
    "g195": ("keyboard_text_bug", False, "none", ""),
    "g196": ("performance_crash", False, "none", ""),
}


def main() -> None:
    g = pd.read_csv(config.GOLDEN_DIR / "golden_unlabelled.csv")
    assert set(g.gid) == set(A), set(g.gid) ^ set(A)
    g["intent"] = g.gid.map(lambda x: A[x][0])
    g["should_escalate"] = g.gid.map(lambda x: A[x][1])
    g["escalation_reason"] = g.gid.map(lambda x: A[x][2])
    g["note"] = g.gid.map(lambda x: A[x][3])
    g.to_csv(config.GOLDEN_DIR / "golden_annotatorA.csv", index=False)
    print("n =", len(g))
    print(g.intent.value_counts().to_string())
    print("\nescalate share:", round(g.should_escalate.mean(), 3), g.escalation_reason.value_counts().to_dict())
    print("hard cases:", int(g.note.str.startswith("HARD").sum()))


if __name__ == "__main__":
    main()
