/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agent/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active agent configuration next to the evaluated configuration (read-only, no secrets) */
        get: operations["agent_profile_api_v1_agent_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Safe runtime configuration (no secrets) */
        get: operations["runtime_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Synthetic demo scenarios and their expected outcomes */
        get: operations["demo_scenarios_api_v1_demo_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Release 1.0.0 scorecard from the frozen release artifacts, by dataset */
        get: operations["evaluation_release_api_v1_evaluation_release_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Headline evaluation results from the frozen Phase 6 artifacts */
        get: operations["evaluation_summary_api_v1_evaluation_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process liveness (no inference, no authentication) */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Knowledge-base aggregates (counts and shares only, no message text) */
        get: operations["knowledge_summary_api_v1_knowledge_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness of runtime components (never calls the LLM; detail only for authenticated callers when auth is on) */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run one conversation through the ResolveAI agent
         * @description Runs the full pipeline (PII redaction, injection check, intent, retrieval, evidence gate, risk flags, deterministic policy, draft / clarify / handoff, verification, output gate) and returns what happened, why, on which evidence, and what happens next. Exactly one action is returned: AUTO_HANDLE, CLARIFICATION_REQUIRED or HUMAN_HANDOFF. A model outage, a model timeout or an exhausted request time budget is not an HTTP error: the agent's deterministic fallback returns a safe clarification or handoff.
         */
        post: operations["resolve_api_v1_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Most recent traces (newest first) */
        get: operations["list_traces_api_v1_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit trace of one agent execution */
        get: operations["get_trace_api_v1_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentTrace */
        AgentTrace: {
            /**
             * Budget S
             * @description wall-clock budget the request ran under (Phase 9)
             */
            budget_s?: number | null;
            /**
             * Config Hash
             * @description hash of the effective configuration for reproducibility
             * @default
             */
            config_hash: string;
            /** Error */
            error?: string | null;
            /** Events */
            events?: components["schemas"]["TraceEvent"][];
            /**
             * Failures
             * @description classified failures: {category, stage, kind}; codes only, never free text (Phase 9)
             */
            failures?: {
                [key: string]: string;
            }[];
            /** Final Decision */
            final_decision?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Latency Ms
             * @description per-stage latency, including total
             */
            latency_ms?: {
                [key: string]: number;
            };
            /** Message Id */
            message_id: string;
            /**
             * Pipeline Version
             * @default
             */
            pipeline_version: string;
            /** Prompt Versions */
            prompt_versions?: {
                [key: string]: string;
            };
            /**
             * Request Id
             * @description correlation id propagated from the API (X-Request-ID)
             * @default
             */
            request_id: string;
            /**
             * Request Meta
             * @description non-identifying request metadata (channel, locale)
             */
            request_meta?: {
                [key: string]: string;
            };
            /** Stage Status */
            stage_status?: {
                [key: string]: string;
            };
            /** Started At */
            started_at: string;
            /** Trace Id */
            trace_id: string;
            /** Usage */
            usage?: components["schemas"]["ModelUsage"][];
            /**
             * Versions
             * @description policy, gate, retrieval, rerank, classifier, model versions
             */
            versions?: {
                [key: string]: string;
            };
        };
        /**
         * ClarificationPacket
         * @description What the agent needs from the customer before it can answer (CLARIFICATION_REQUIRED).
         */
        ClarificationPacket: {
            /**
             * Already Provided
             * @description details found in the conversation, therefore not asked again
             */
            already_provided?: string[];
            /** Alternatives */
            alternatives?: string[];
            /**
             * Confidence Band
             * @default LOW
             */
            confidence_band: string;
            /**
             * Evidence Level
             * @default INSUFFICIENT
             */
            evidence_level: string;
            /**
             * Evidence Reason
             * @default
             */
            evidence_reason: string;
            /**
             * Evidence Summary
             * @default
             */
            evidence_summary: string;
            /**
             * Intent Confidence
             * @default 0
             */
            intent_confidence: number;
            /** Intent Hypothesis */
            intent_hypothesis: string;
            /**
             * Missing Information
             * @description details the question asks for
             */
            missing_information?: string[];
            /**
             * Policy Version
             * @default
             */
            policy_version: string;
            /**
             * Question
             * @description the single customer-facing clarifying question
             */
            question: string;
            /** Reason Code */
            reason_code: string;
            /**
             * Trace Id
             * @default
             */
            trace_id: string;
            /**
             * Why
             * @description why the agent did not answer: evidence or understanding gap
             */
            why: string;
        };
        /** ConversationContext */
        ConversationContext: {
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /**
             * Turns
             * @description prior turns, oldest first
             */
            turns?: components["schemas"]["ConversationTurn"][];
        };
        /** ConversationTurn */
        ConversationTurn: {
            /**
             * Role
             * @enum {string}
             */
            role: "customer" | "brand";
            /** Text */
            text: string;
        };
        /** ConversationView */
        ConversationView: {
            /** @description earlier turns AFTER PII redaction */
            context: components["schemas"]["ConversationContext"];
            /** @description the current customer message AFTER PII redaction */
            message: components["schemas"]["CustomerMessage"];
        };
        /**
         * CustomerMessage
         * @description One inbound customer message, already PII-redacted.
         */
        CustomerMessage: {
            /** Language Hint */
            language_hint?: string | null;
            /** Message Id */
            message_id: string;
            /**
             * Pii Counts
             * @description redaction counts by type; the raw values are never stored
             */
            pii_counts?: {
                [key: string]: number;
            };
            /** Received At */
            received_at?: string | null;
            /**
             * Text
             * @description PII-redacted customer text (typed tokens such as <PHONE>)
             */
            text: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Details */
            details?: unknown;
            /** Error Code */
            error_code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Trace Id */
            trace_id?: string | null;
        };
        /** EscalationResult */
        EscalationResult: {
            /**
             * Clarification Allowed
             * @description policy permits a clarifying question instead of a handoff
             * @default false
             */
            clarification_allowed: boolean;
            /**
             * Decision
             * @enum {string}
             */
            decision: "auto_handle" | "escalate";
            /**
             * Policy Version
             * @default policy-v1
             */
            policy_version: string;
            /**
             * Reason
             * @description human-readable, customer-safe reason
             */
            reason: string;
            /**
             * Reason Code
             * @enum {string}
             */
            reason_code: "safety" | "prompt_injection" | "legal_media" | "abusive_threatening" | "private_info" | "account_access" | "payment_billing" | "sensitive_action" | "hardware" | "repeat_contact" | "human_requested" | "vague_hostile" | "taxonomy_gap_risk" | "conflicting_evidence" | "low_confidence" | "insufficient_context" | "insufficient_evidence" | "grounding_failed" | "verification_failed" | "output_gate" | "llm_unavailable" | "model_timeout" | "dependency_failure" | "audit_unavailable" | "none";
            /**
             * Rule
             * @description name of the deterministic rule that fired
             */
            rule: string;
        };
        /**
         * EvidenceItem
         * @description One historical (customer message -> brand reply) pair with full provenance.
         */
        EvidenceItem: {
            /** Brand Reply */
            brand_reply: string;
            /** Created At */
            created_at: string;
            /** Customer Message */
            customer_message: string;
            /**
             * Dm Handoff
             * @default false
             */
            dm_handoff: boolean;
            /**
             * Evidence Id
             * @description brand_tweet_id of the historical reply (dataset-assigned, deterministic)
             */
            evidence_id: string;
            /**
             * Outcome
             * @default none
             * @enum {string}
             */
            outcome: "positive" | "negative" | "mixed" | "none";
            quality: components["schemas"]["EvidenceQuality"];
            /** Rank */
            rank: number;
            /**
             * Ranks
             * @description rank in each underlying ranked list (bm25, dense)
             */
            ranks?: {
                [key: string]: number;
            };
            /**
             * Retrieval Method
             * @description bm25 | dense:<model> | hybrid:<model> | hybrid+outcome:<model>
             */
            retrieval_method: string;
            /**
             * Retrieval Source
             * @description which index surfaced the item: customer (problem similarity), reply (resolution similarity), pair, or dual (both)
             * @default customer
             * @enum {string}
             */
            retrieval_source: "customer" | "reply" | "pair" | "dual";
            /**
             * Scores
             * @description bm25, dense, rrf, outcome_bonus, final
             */
            scores?: {
                [key: string]: number;
            };
            /**
             * Source
             * @description dataset provenance: dataset, brand, preprocessing_version, kb_hash
             */
            source?: {
                [key: string]: string;
            };
            /**
             * Source Row Id
             * @description row id inside the shipped subsample: customer_tweet_id
             */
            source_row_id: string;
            /**
             * Substantive
             * @default true
             */
            substantive: boolean;
            /**
             * Thread Id
             * @description customer_tweet_id of the historical customer message (thread anchor)
             */
            thread_id: string;
        };
        /**
         * EvidenceQuality
         * @description Operational classification of one candidate. Signals, not ground truth.
         */
        EvidenceQuality: {
            /**
             * Action Class
             * @default other
             * @enum {string}
             */
            action_class: "update" | "restart" | "reset" | "settings" | "article" | "ask_info" | "dm_handoff" | "other";
            /**
             * Candidate Intent
             * @description weak (keyword) intent of the candidate; noisy by construction
             * @default
             */
            candidate_intent: string;
            /**
             * Intent Match
             * @description candidate weak intent == query intent when the query intent is known
             */
            intent_match?: boolean | null;
            /**
             * Lexical Relevance
             * @description BM25 score (0 when no lexical overlap)
             */
            lexical_relevance: number;
            /**
             * Quality
             * @default weak
             * @enum {string}
             */
            quality: "strong" | "usable" | "weak";
            /**
             * Resolution Relevance
             * @description substantive reply (not a DM handoff) that states an action
             * @default false
             */
            resolution_relevance: boolean;
            /**
             * Same Customer
             * @default false
             */
            same_customer: boolean;
            /**
             * Semantic Relevance
             * @description dense cosine between query and candidate customer message
             */
            semantic_relevance: number;
            /**
             * Temporal Eligible
             * @default true
             */
            temporal_eligible: boolean;
        };
        /**
         * EvidenceRef
         * @description Citation for a customer-facing reply: one retrieved historical case the reply was drafted from (Phase 7 API contract).
         */
        EvidenceRef: {
            /** Action Class */
            action_class: string;
            /**
             * Created At
             * @description timestamp of the historical case (always before the knowledge-base cutoff)
             */
            created_at: string;
            /**
             * Evidence Id
             * @description brand_tweet_id of the historical reply
             */
            evidence_id: string;
            /**
             * Outcome
             * @default none
             */
            outcome: string;
            /** Rank */
            rank: number;
            /** Resolution Bearing */
            resolution_bearing: boolean;
            /** Retrieval Source */
            retrieval_source: string;
            /**
             * Similarity
             * @description cosine similarity between the query and the historical customer message
             */
            similarity: number;
            /** Source Row Id */
            source_row_id: string;
            /**
             * Thread Id
             * @description customer_tweet_id of the historical customer message
             */
            thread_id: string;
        };
        /** EvidenceSet */
        EvidenceSet: {
            /**
             * Consistency
             * @default no_resolution
             * @enum {string}
             */
            consistency: "consistent" | "mixed_resolution" | "no_resolution";
            /**
             * Gate Version
             * @default
             */
            gate_version: string;
            /**
             * Items
             * @description ranked candidates (retrieved)
             */
            items?: components["schemas"]["EvidenceItem"][];
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /**
             * N Relevant
             * @default 0
             */
            n_relevant: number;
            /**
             * N Retrieved
             * @default 0
             */
            n_retrieved: number;
            /**
             * Quarantined Ids
             * @description retrieved items excluded before the gate because their text reads as instructions (Phase 9)
             */
            quarantined_ids?: string[];
            /**
             * Query
             * @default
             */
            query: string;
            /** Query Intent */
            query_intent?: string | null;
            /**
             * Resolution Candidates
             * @description resolution clusters, best first
             */
            resolution_candidates?: components["schemas"]["ResolutionCandidate"][];
            /**
             * Resolution Confidence
             * @description measurable evidence score (not an LLM probability); formula in retrieval/resolution.py
             * @default 0
             */
            resolution_confidence: number;
            /**
             * Retriever
             * @default
             */
            retriever: string;
            signals?: components["schemas"]["SufficiencySignals"] | null;
            /**
             * Sufficiency Level
             * @default INSUFFICIENT
             * @enum {string}
             */
            sufficiency_level: "INSUFFICIENT" | "WEAK" | "SUFFICIENT" | "STRONG";
            /**
             * Sufficiency Reason
             * @default no_relevant_evidence
             * @enum {string}
             */
            sufficiency_reason: "strong_consistent_evidence" | "weak_similarity" | "insufficient_resolution_evidence" | "conflicting_evidence" | "ambiguous_intent" | "no_relevant_evidence" | "customer_history_risk" | "insufficient_query" | "mixed_resolution" | "weak_resolution_evidence" | "not_applicable";
            /**
             * Sufficient
             * @default false
             */
            sufficient: boolean;
        };
        /**
         * HandoffPacket
         * @description What a human agent receives when the case is escalated. Self-contained: readable without re-running the agent.
         */
        HandoffPacket: {
            /** Alternatives */
            alternatives?: string[];
            /** Confidence */
            confidence: number;
            /**
             * Confidence Band
             * @default LOW
             */
            confidence_band: string;
            /** Customer Issue */
            customer_issue: string;
            /**
             * Draft If Any
             * @description a generated draft that failed verification, for the human to reuse or discard
             */
            draft_if_any?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceItem"][];
            /**
             * Evidence Level
             * @default INSUFFICIENT
             */
            evidence_level: string;
            /**
             * Evidence Reason
             * @default
             */
            evidence_reason: string;
            /**
             * Evidence Sufficient
             * @default false
             */
            evidence_sufficient: boolean;
            /**
             * Evidence Summary
             * @default
             */
            evidence_summary: string;
            /** Historical Examples */
            historical_examples?: components["schemas"]["HistoricalExample"][];
            /** Intent */
            intent: string;
            /**
             * Policy Version
             * @default
             */
            policy_version: string;
            reason: components["schemas"]["EscalationResult"];
            /**
             * Recommended Next Action
             * @default
             */
            recommended_next_action: string;
            /**
             * Resolution Candidates
             * @description clustered historical resolutions with their source ids (Phase 5)
             */
            resolution_candidates?: components["schemas"]["ResolutionCandidate"][];
            /**
             * Resolution Confidence
             * @default 0
             */
            resolution_confidence: number;
            risk: components["schemas"]["RiskFlags"];
            /**
             * Suggested Opening
             * @default
             */
            suggested_opening: string;
            /**
             * Summary
             * @description conversation summary, customer-safe
             */
            summary: string;
            /**
             * Trace Id
             * @default
             */
            trace_id: string;
            /** Unresolved Questions */
            unresolved_questions?: string[];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Env */
            env: string;
            /** Service */
            service: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Uptime S */
            uptime_s: number;
            /** Version */
            version: string;
        };
        /** HistoricalExample */
        HistoricalExample: {
            /** Action Class */
            action_class: string;
            /** Brand Reply */
            brand_reply: string;
            /** Customer Message */
            customer_message: string;
            /** Evidence Id */
            evidence_id: string;
            /** Outcome */
            outcome: string;
            /** Similarity */
            similarity: number;
            /** Thread Id */
            thread_id: string;
        };
        /**
         * IntentResult
         * @description Classifier output. `intent` is the primary (predicted) intent; probabilities are calibrated when `calibrated` is True.
         */
        IntentResult: {
            /**
             * Calibrated
             * @default false
             */
            calibrated: boolean;
            /**
             * Calibration
             * @description method, temperature, dev ECE
             */
            calibration?: {
                [key: string]: number | string;
            };
            /** Confidence */
            confidence: number;
            /**
             * Confidence Band
             * @default LOW
             * @enum {string}
             */
            confidence_band: "HIGH" | "MEDIUM" | "LOW";
            /**
             * Context Used
             * @default false
             */
            context_used: boolean;
            /**
             * Insufficient Context
             * @description short reply with no informative prior turn; intent is a guess
             * @default false
             */
            insufficient_context: boolean;
            /** Intent */
            intent: string;
            /**
             * Method
             * @default embed_lr
             * @enum {string}
             */
            method: "majority" | "keyword" | "tfidf_lr" | "embed_lr" | "llm" | "ensemble";
            /**
             * Multi Intent
             * @default false
             */
            multi_intent: boolean;
            /**
             * Second Opinion
             * @description LLM intent when consulted; never overrides silently
             */
            second_opinion?: string | null;
            /**
             * Second Opinion Applied
             * @default false
             */
            second_opinion_applied: boolean;
            /** Secondary Intents */
            secondary_intents?: string[];
            /**
             * Taxonomy Gap
             * @description prediction fell to the fallback class with a flat distribution
             * @default false
             */
            taxonomy_gap: boolean;
            /**
             * Top3
             * @description top alternatives with calibrated probabilities
             */
            top3?: [
                string,
                number
            ][];
        };
        /** ModelUsage */
        ModelUsage: {
            /**
             * Budget Exhausted
             * @default 0
             */
            budget_exhausted: number;
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
            /**
             * Calls
             * @default 0
             */
            calls: number;
            /**
             * Errors
             * @default 0
             */
            errors: number;
            /** Estimated Cost Usd */
            estimated_cost_usd?: number | null;
            /**
             * Fallbacks
             * @default 0
             */
            fallbacks: number;
            /** Model */
            model: string;
            /**
             * Retries
             * @default 0
             */
            retries: number;
            /**
             * Timeouts
             * @default 0
             */
            timeouts: number;
            /**
             * Tokens In
             * @default 0
             */
            tokens_in: number;
            /**
             * Tokens Out
             * @default 0
             */
            tokens_out: number;
        };
        /**
         * OutcomeView
         * @description WHAT happened, WHY, on WHAT evidence, and WHAT happens next (from the agent's DecisionSummary plus gate details).
         */
        OutcomeView: {
            /**
             * Action
             * @enum {string}
             */
            action: "AUTO_HANDLE" | "HUMAN_HANDOFF" | "CLARIFICATION_REQUIRED";
            /** Autonomous Response Allowed */
            autonomous_response_allowed: boolean;
            /** Blocking Checks */
            blocking_checks?: string[];
            /** Evidence Basis */
            evidence_basis: string;
            /** Next Step */
            next_step: string;
            /**
             * Output Gate
             * @description every output-gate check and whether it passed
             */
            output_gate?: {
                [key: string]: boolean;
            };
            /** Policy Version */
            policy_version: string;
            /** Reason Code */
            reason_code: string;
            /** Rule */
            rule: string;
            /** What Happened */
            what_happened: string;
            /** Why */
            why: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Components */
            components: {
                [key: string]: unknown;
            };
            /** Ready */
            ready: boolean;
        };
        /** RequestMetadata */
        RequestMetadata: {
            /** Channel */
            channel?: ("twitter" | "email" | "chat" | "web" | "api") | null;
            /**
             * Customer Id Hash
             * @description SHA-256 hex of the caller's customer id. Validated and then discarded: never stored, traced or sent to a model. Raw ids or emails are rejected by the pattern.
             */
            customer_id_hash?: string | null;
            /**
             * Locale
             * @description e.g. en-US; recorded in the trace
             */
            locale?: string | null;
            /**
             * Timestamp
             * @description when the customer message was sent; historical evidence must predate it
             */
            timestamp?: string | null;
        };
        /**
         * ResolutionCandidate
         * @description A cluster of historical replies that prescribe the same kind of resolution. Never fabricated: every candidate is the
         *     text of a real historical reply plus the ids of the replies that agree with it.
         */
        ResolutionCandidate: {
            /**
             * Action Class
             * @enum {string}
             */
            action_class: "update" | "restart" | "reset" | "settings" | "article" | "ask_info" | "dm_handoff" | "other";
            /** Evidence Ids */
            evidence_ids: string[];
            /** Mean Similarity */
            mean_similarity: number;
            /**
             * Positive Outcomes
             * @default 0
             */
            positive_outcomes: number;
            /** Representative Id */
            representative_id: string;
            /** Representative Reply */
            representative_reply: string;
            /**
             * Share
             * @description share of resolution-bearing support this cluster holds
             */
            share: number;
            /** Support Count */
            support_count: number;
        };
        /**
         * ResolveRequest
         * @description One customer conversation, oldest turn first, ending with the customer message to handle. Unknown fields (including any
         *     attempt to supply 'evidence', 'policy' or 'system' fields) are rejected: evidence only comes from the retrieval index.
         * @example {
         *       "conversation": [
         *         {
         *           "role": "customer",
         *           "text": "My iPhone keeps changing \"it\" to \"I.T\" whenever I type. How do I fix this autocorrect bug?"
         *         }
         *       ],
         *       "metadata": {
         *         "channel": "twitter",
         *         "locale": "en-US"
         *       }
         *     }
         */
        ResolveRequest: {
            /** Conversation */
            conversation: components["schemas"]["TurnIn"][];
            metadata?: components["schemas"]["RequestMetadata"] | null;
        };
        /** ResolveResponse */
        ResolveResponse: {
            /**
             * Action
             * @enum {string}
             */
            action: "AUTO_HANDLE" | "HUMAN_HANDOFF" | "CLARIFICATION_REQUIRED";
            /** @description present only for CLARIFICATION_REQUIRED */
            clarification?: components["schemas"]["ClarificationPacket"] | null;
            conversation: components["schemas"]["ConversationView"];
            evidence: components["schemas"]["EvidenceSet"];
            /** @description present only for HUMAN_HANDOFF */
            handoff?: components["schemas"]["HandoffPacket"] | null;
            intent: components["schemas"]["IntentResult"];
            /** Latency Ms */
            latency_ms: {
                [key: string]: number;
            };
            outcome: components["schemas"]["OutcomeView"];
            /** Request Id */
            request_id: string;
            response: components["schemas"]["ResponseView"];
            risk: components["schemas"]["RiskFlags"];
            /** Stage Status */
            stage_status: {
                [key: string]: string;
            };
            /** Trace Id */
            trace_id: string;
            usage: components["schemas"]["UsageSummary"];
            verification?: components["schemas"]["VerificationResult"] | null;
            versions: components["schemas"]["RuntimeVersions"];
        };
        /** ResponseView */
        ResponseView: {
            /**
             * Draft Attempts
             * @default 0
             */
            draft_attempts: number;
            /**
             * Evidence Refs
             * @description citations for an auto_reply; empty for every other kind
             */
            evidence_refs?: components["schemas"]["EvidenceRef"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "auto_reply" | "template_reply" | "clarifying_question" | "handoff_notice";
            /**
             * Sent Automatically
             * @description true only for AUTO_HANDLE
             */
            sent_automatically: boolean;
            /**
             * Text
             * @description customer-facing text; for a handoff it is only a holding notice, never an answer
             */
            text: string;
        };
        /**
         * RiskFlags
         * @description Signals extracted for the deterministic policy. The LLM may fill these; it never decides from them.
         *     Every field is a FLAG; the escalation decision is made by resolveai.policy.
         */
        RiskFlags: {
            /**
             * Abusive Threatening
             * @default false
             */
            abusive_threatening: boolean;
            /**
             * Account Access Risk
             * @default false
             */
            account_access_risk: boolean;
            /**
             * Conflicting Evidence
             * @default false
             */
            conflicting_evidence: boolean;
            /**
             * High Frustration
             * @default false
             */
            high_frustration: boolean;
            /**
             * High Impact
             * @default false
             */
            high_impact: boolean;
            /**
             * Insufficient Context
             * @default false
             */
            insufficient_context: boolean;
            /**
             * Is Actionable
             * @default true
             */
            is_actionable: boolean;
            /**
             * Legal Or Media Threat
             * @default false
             */
            legal_or_media_threat: boolean;
            /**
             * Needs Private Info
             * @default false
             */
            needs_private_info: boolean;
            /**
             * Payment Billing Risk
             * @default false
             */
            payment_billing_risk: boolean;
            /**
             * Physical Damage
             * @default false
             */
            physical_damage: boolean;
            /**
             * Privacy Concern
             * @default false
             */
            privacy_concern: boolean;
            /**
             * Prompt Injection
             * @default false
             */
            prompt_injection: boolean;
            /**
             * Repeat Contact
             * @default false
             */
            repeat_contact: boolean;
            /**
             * Safety Concern
             * @default false
             */
            safety_concern: boolean;
            /**
             * Security Concern
             * @default false
             */
            security_concern: boolean;
            /**
             * Sensitive Action Required
             * @default false
             */
            sensitive_action_required: boolean;
            /**
             * Source
             * @default rules
             * @enum {string}
             */
            source: "llm" | "rules" | "llm+rules" | "fallback";
            /**
             * Summary
             * @description one-line operational summary, customer-safe
             * @default
             */
            summary: string;
        };
        /**
         * RuntimeVersions
         * @description Everything needed to reproduce a decision: component versions, prompt versions, model and a hash of the effective config.
         */
        RuntimeVersions: {
            /**
             * Classifier
             * @description first 12 hex characters of the frozen classifier artifact's SHA-256
             */
            classifier: string;
            /** Config Hash */
            config_hash: string;
            /** Evidence Gate */
            evidence_gate: string;
            /** Model */
            model?: string | null;
            /** Output Gate */
            output_gate: string;
            /** Pipeline */
            pipeline: string;
            /** Policy */
            policy: string;
            /** Prompts */
            prompts?: {
                [key: string]: string;
            };
            /** Rerank */
            rerank: string;
            /** Retrieval */
            retrieval: string;
        };
        /**
         * SufficiencySignals
         * @description Measurable inputs to the gate; exposed so the Trust layer and the UI can inspect the decision.
         */
        SufficiencySignals: {
            /** Action Classes */
            action_classes?: {
                [key: string]: number;
            };
            /**
             * Conflicting
             * @default false
             */
            conflicting: boolean;
            /**
             * Intent Agreement
             * @description share of top-k sharing the modal candidate intent
             */
            intent_agreement: number;
            /**
             * Modal Intent
             * @default
             */
            modal_intent: string;
            /** N Relevant */
            n_relevant: number;
            /** N Retrieved */
            n_retrieved: number;
            /**
             * Query Content Tokens
             * @description content tokens in the query after removing URLs, redaction tokens and stopwords
             * @default 0
             */
            query_content_tokens: number;
            /**
             * Query Intent Agreement
             * @description share of top-k matching the query intent, if known
             */
            query_intent_agreement?: number | null;
            /**
             * Query Symptom Tokens
             * @description query tokens naming a symptom/feature (gate-v3 specificity guard)
             * @default 0
             */
            query_symptom_tokens: number;
            /**
             * Resolution Bearing
             * @description substantive cases with a positive outcome signal
             */
            resolution_bearing: number;
            /**
             * Same Customer Count
             * @default 0
             */
            same_customer_count: number;
            /**
             * Similarity Margin
             * @description top-1 cosine minus top-3 cosine
             */
            similarity_margin: number;
            /**
             * Support Count
             * @description independent, resolution-bearing substantive cases above the support similarity
             */
            support_count: number;
            /** Top Similarity */
            top_similarity: number;
        };
        /** TraceEvent */
        TraceEvent: {
            /** Component */
            component: string;
            /**
             * Data
             * @description ids, scores, evidence refs, gate verdicts, decisions, token usage
             */
            data?: {
                [key: string]: unknown;
            };
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            name: components["schemas"]["TraceEventName"];
            /**
             * Status
             * @description ok | skipped | failed | fallback
             * @default ok
             */
            status: string;
            /**
             * Ts
             * @description ISO-8601 UTC timestamp
             */
            ts: string;
        };
        /**
         * TraceEventName
         * @enum {string}
         */
        TraceEventName: "request_received" | "pii_redacted" | "injection_checked" | "clarification_created" | "context_built" | "intent_classified" | "intent_predicted" | "second_opinion_used" | "risk_extracted" | "risk_flags_extracted" | "retrieval_started" | "retrieval_completed" | "retrieval_skipped" | "evidence_gate" | "evidence_evaluated" | "evidence_quarantined" | "escalation_decided" | "draft_generated" | "grounding_checked" | "response_verified" | "policy_checked" | "decision_made" | "output_allowed" | "handoff" | "handoff_created" | "response_returned" | "model_call_failed" | "dependency_failed" | "execution_failed" | "error" | "fallback";
        /** TraceListResponse */
        TraceListResponse: {
            /** Items */
            items: components["schemas"]["TraceSummary"][];
            /** Limit */
            limit: number;
        };
        /** TraceSummary */
        TraceSummary: {
            /** Channel */
            channel?: string | null;
            /** Confidence Band */
            confidence_band?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Estimated Cost Usd
             * @description estimated model cost of the execution at list price (from the trace's usage records)
             */
            estimated_cost_usd?: number | null;
            /**
             * Evidence Level
             * @description INSUFFICIENT | WEAK | SUFFICIENT | STRONG
             */
            evidence_level?: string | null;
            /** Evidence Sufficient */
            evidence_sufficient?: boolean | null;
            /** Final Decision */
            final_decision?: string | null;
            /**
             * Intent
             * @description final intent (after an applied second opinion)
             */
            intent?: string | null;
            /** Intent Confidence */
            intent_confidence?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Llm Calls */
            llm_calls?: number | null;
            /**
             * Pipeline Version
             * @default
             */
            pipeline_version: string;
            /** Policy Version */
            policy_version?: string | null;
            /** Reason Code */
            reason_code?: string | null;
            /**
             * Request Id
             * @default
             */
            request_id: string;
            /** Risk Flags */
            risk_flags?: string[];
            /**
             * Rule
             * @description policy rule that fired at the policy stage
             */
            rule?: string | null;
            /** Started At */
            started_at: string;
            /** Trace Id */
            trace_id: string;
        };
        /** TurnIn */
        TurnIn: {
            /**
             * Role
             * @description who wrote the turn; the LAST turn must be the customer's
             * @enum {string}
             */
            role: "customer" | "brand";
            /**
             * Text
             * @description raw turn text; redacted by the agent before any storage or model call
             */
            text: string;
        };
        /** UsageSummary */
        UsageSummary: {
            /**
             * Budget Exhausted
             * @default 0
             */
            budget_exhausted: number;
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
            /**
             * Estimated Cost Usd
             * @default 0
             */
            estimated_cost_usd: number;
            /**
             * Fallbacks
             * @default 0
             */
            fallbacks: number;
            /**
             * Live Calls
             * @default 0
             */
            live_calls: number;
            /**
             * Llm Calls
             * @default 0
             */
            llm_calls: number;
            /**
             * Model Errors
             * @default 0
             */
            model_errors: number;
            /**
             * Retries
             * @default 0
             */
            retries: number;
            /**
             * Timeouts
             * @default 0
             */
            timeouts: number;
            /**
             * Tokens In
             * @default 0
             */
            tokens_in: number;
            /**
             * Tokens Out
             * @default 0
             */
            tokens_out: number;
        };
        /** VerificationIssue */
        VerificationIssue: {
            /** Check */
            check: string;
            /** Detail */
            detail: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "blocking";
        };
        /**
         * VerificationResult
         * @description Grounded-response verification. `verified` is False if any blocking issue exists.
         */
        VerificationResult: {
            /**
             * Attempts
             * @default 1
             */
            attempts: number;
            /**
             * Coverage
             * @description share of response content words found in cited evidence
             * @default 0
             */
            coverage: number;
            /**
             * Evidence Refs
             * @description evidence_ids the response is supported by
             */
            evidence_refs?: string[];
            /** Issues */
            issues?: components["schemas"]["VerificationIssue"][];
            /**
             * Method
             * @default lexical
             * @enum {string}
             */
            method: "lexical" | "lexical+llm";
            /**
             * Severity
             * @default none
             * @enum {string}
             */
            severity: "none" | "info" | "warning" | "blocking";
            /** Verified */
            verified: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    agent_profile_api_v1_agent_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Length Required */
            411: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    runtime_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Length Required */
            411: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    demo_scenarios_api_v1_demo_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Length Required */
            411: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    evaluation_release_api_v1_evaluation_release_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Length Required */
            411: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    evaluation_summary_api_v1_evaluation_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Length Required */
            411: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    knowledge_summary_api_v1_knowledge_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Length Required */
            411: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    resolve_api_v1_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Length Required */
            411: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_traces_api_v1_traces_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description any capitalization */
                action?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceListResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Length Required */
            411: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_trace_api_v1_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentTrace"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Length Required */
            411: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
