/**
 * Plain-text handoff summary for pasting into a helpdesk ticket. Built only from the API's HandoffPacket and outcome.
 * The API already redacts personal data; free text is scrubbed again here before it reaches the clipboard (defence in depth).
 */
import type { ResolveResponse } from "@/lib/api/types";
import { EVIDENCE_LEVEL_META, RISK_FLAG_LABELS, evidenceLevel, handoffCategory, intentLabel, reasonMeta } from "@/lib/labels";

export function activeRiskFlags(risk: Record<string, unknown> | null | undefined): string[] {
  if (!risk) return [];
  return Object.keys(RISK_FLAG_LABELS).filter((k) => risk[k] === true);
}

/** Mirrors the placeholders of resolveai/trust/pii.py (order matters: order ids and cards before phone numbers). */
const PII_PATTERNS: [string, RegExp][] = [
  ["EMAIL", /[\w.+-]+@[\w-]+\.[\w.-]+/g],
  ["ORDER_ID", /\b\d{3}-\d{7}-\d{7}\b/g],
  ["CARD", /\b(?:\d[ -]?){13,19}\b/g],
  ["LONG_ID", /\b(?=[A-Z0-9-]{10,}\b)(?=[A-Z0-9-]*\d)(?=[A-Z0-9-]*[A-Z])[A-Z0-9-]{10,}\b/g],
  ["PHONE", /(?<!\d)(?<!\d\.)(?:\+?\d{1,3}[\s.-]?)?(?:\(?\d{3}\)?[\s.-]?)\d{3}[\s.-]?\d{4}(?!\d)(?!\.\d)/g],
];

export function scrubPii(text: string): string {
  return PII_PATTERNS.reduce((t, [name, re]) => t.replace(re, `<${name}>`), text);
}

export function handoffSummaryText(r: ResolveResponse): string {
  const h = r.handoff;
  if (!h) return "";
  const s = scrubPii;
  const reason = reasonMeta(h.reason.reason_code);
  const level = evidenceLevel(h.evidence_level);
  const flags = activeRiskFlags(h.risk as unknown as Record<string, unknown>).map((f) => RISK_FLAG_LABELS[f]);
  const lines = [
    "ResolveAI handoff (generated by the agent; no automatic reply was given)",
    `Trace: ${h.trace_id}`,
    `Queue: ${handoffCategory(h.reason.reason_code, h.reason.rule)} · severity ${reason.severity}`,
    `Reason: ${reason.label} [${h.reason.reason_code}; rule ${h.reason.rule}; ${h.policy_version}]`,
    `Why: ${s(h.reason.reason)}`,
    "",
    `Customer issue (PII redacted): ${s(h.customer_issue)}`,
    ...(h.summary && h.summary !== h.customer_issue ? [`Conversation summary: ${s(h.summary)}`] : []),
    `Context: ${r.conversation.context.turns.length ? `${r.conversation.context.turns.length} earlier turn(s) before this message` : "first message in the conversation"}`,
    `Intent: ${intentLabel(h.intent)} (${h.intent}), confidence ${h.confidence.toFixed(2)}, ${h.confidence_band} band`,
    `Risk flags: ${flags.length ? flags.join(", ") : "none"}`,
    `Evidence: ${EVIDENCE_LEVEL_META[level].label} (${h.evidence_reason}); resolution confidence ${h.resolution_confidence.toFixed(2)}`,
    "",
    `Recommended next action: ${s(h.recommended_next_action)}`,
  ];
  if (h.unresolved_questions.length) {
    lines.push("Unresolved questions:", ...h.unresolved_questions.map((q) => `- ${s(q)}`));
  }
  if (h.suggested_opening) lines.push(`Suggested opening: ${s(h.suggested_opening)}`);
  if (h.historical_examples.length) {
    lines.push("Historical examples (not verified as solutions for this customer):", ...h.historical_examples.slice(0, 3).map((e) => `- case ${e.evidence_id} (${e.action_class}, similarity ${e.similarity.toFixed(2)})`));
  }
  if (h.draft_if_any) lines.push(`Blocked draft (do not send without review): ${s(h.draft_if_any)}`);
  return lines.join("\n");
}
